name: Fisrt_pull_request
on:
  pull_request: 

jobs:
  TareaPull1:
    runs-on: ubuntu-latest

    steps:
      - name: Datos del Pull Request
        run:
          echo "Datos destino (Base) ${{ github.event.pull_request.base.ref }}"
          echo "Datos origen (Head) ${{ github.event.pull_request.head.ref }}"
          echo "Título ${{ github.event.pull_request.title }}"
          echo "Contenido ${{ github.event.pull_request.body }}"
          echo "Estado ${{ github.event.pull_request.state }}"
          echo "Fusionado ${{ github.event.pull_request.merged }}"
          
