# Mirza Natzielly Morales Lezama
name: WorkFlow Mirza Morales

on: 
  workflow_dispatch:

jobs:
  Tarea1:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello 
        run: echo "Hello World"
        
      - name: Fecha
        run: date

      - name: Listar archivos
        run: ls -la
    
